// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { GetFruitsError, GetFruitsResponse, CreateFruitData, CreateFruitError, CreateFruitResponse, GetFruitByIdData, GetFruitByIdError, GetFruitByIdResponse, GetFruitByNameData, GetFruitByNameError, GetFruitByNameResponse, GetHelloError, GetHelloResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Fruits
 */
export const getFruits = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFruitsResponse, GetFruitsError, ThrowOnError>({
        ...options,
        url: '/fruits'
    });
};

/**
 * Create Fruit
 */
export const createFruit = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateFruitData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateFruitResponse, CreateFruitError, ThrowOnError>({
        ...options,
        url: '/fruits'
    });
};

/**
 * Get Fruit By Id
 */
export const getFruitById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetFruitByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFruitByIdResponse, GetFruitByIdError, ThrowOnError>({
        ...options,
        url: '/fruits/{id}'
    });
};

/**
 * Get Fruit By Name
 */
export const getFruitByName = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetFruitByNameData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFruitByNameResponse, GetFruitByNameError, ThrowOnError>({
        ...options,
        url: '/fruits/{name}'
    });
};

/**
 * Hello
 */
export const getHello = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHelloResponse, GetHelloError, ThrowOnError>({
        ...options,
        url: "/hello",
    });
};

