// This file is auto-generated by @hey-api/openapi-ts

export type Fruit = {
    id?: number;
    name?: string;
    description?: string;
};

export type FruitsResponse = {
    fruits?: Array<Fruit>;
};

export type GetFruitsResponse = (FruitsResponse);

export type GetFruitsError = unknown;

export type CreateFruitData = {
    body: Fruit;
};

export type CreateFruitResponse = (unknown);

export type CreateFruitError = unknown;

export type GetFruitByIdData = {
    path: {
        id: number;
    };
};

export type GetFruitByIdResponse = ((Fruit | null));

export type GetFruitByIdError = unknown;

export type GetFruitByNameData = {
    path: {
        name: string;
    };
};

export type GetFruitByNameResponse = ((Fruit | null));

export type GetFruitByNameError = unknown;

export type GetHelloResponse = (string);

export type GetHelloError = unknown;